[versions]
# libraries
spring-boot = "4.0.1"
spring-cloud = "2025.1.0"
cosid = "3.0.2"
simba = "3.0.0"
cosec = "4.1.1"
guava = "33.5.0-jre"
kotlin-logging = "7.0.14"
commons-io = "2.21.0"
springdoc = "3.0.1"
junit = "6.0.2"
fluent-assert = "0.2.6"
mockk = "1.14.7"
jmh = "1.37"
# plugins
detekt = "1.23.8"
dokka = "2.1.0"
kotlin = "2.3.0"
publish-Plugin = "2.0.0"
jmh-plugin = "0.7.3"
[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
cosid-bom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
simba-bom = { module = "me.ahoo.simba:simba-bom", version.ref = "simba" }
cosec-bom = { module = "me.ahoo.cosec:cosec-bom", version.ref = "cosec" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
fluent-assert-bom = { module = "me.ahoo.test:fluent-assert-bom", version.ref = "fluent-assert" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-Plugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }

